# Generated by Django 2.1.10 on 2019-08-08 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wechange_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Terminated.'), (1, 'Cancelled, but still active'), (2, 'Active'), (3, 'Waiting, becoming active at next payment due date')], default=0, editable=False, help_text='A subscription can only ever go from higher number states to lower number states, never back up again!', verbose_name='Subscription State')),
                ('has_problems', models.BooleanField(default=False, help_text="An indicator flag that there were payment problems with the subscription's last payment. The subscription stays in active state however!", verbose_name='Has Problems')),
                ('next_due_date', models.DateField(blank=True, help_text='Set to the next date whenever a payment is processed successfully.', null=True, verbose_name='Next due date')),
                ('amount', models.FloatField(default='0.0', editable=False, verbose_name='Amount', help_text='For security reasons, the amount can not be changed through the admin interface!')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscription',
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_reference_payment',
            field=models.BooleanField(default=True, editable=False, help_text='Is this the reference (first) payment in a series or a subscription payment derived from a reference payment?', verbose_name='Is reference payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='revoked',
            field=models.BooleanField(default=False, verbose_name='Has been revoked'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='backend',
            field=models.CharField(max_length=255, verbose_name='Backend class used'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_payment',
            field=models.ForeignKey(help_text='The most recent payment made.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wechange_payments.Payment', verbose_name='Last Payment'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reference_payment',
            field=models.OneToOneField(help_text='The first payment for this subscription, which is also used to book any future payments.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wechange_payments.Payment', verbose_name='Reference Payment'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='wechange_payments.Subscription'),
        ),
    ]
