# Generated by Django 2.1.10 on 2019-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechange_payments', '0002_auto_20190808_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='terminated',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created'),
        ),
    ]
