# Generated by Django 2.1.10 on 2019-09-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechange_payments', '0003_subscription_terminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_action_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Action At'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'Payment initiated but not completed by user yet'), (2, 'Payment processing'), (3, 'Successfully paid'), (101, 'Failed'), (102, 'Retracted'), (103, 'Canceled')], default=0, editable=False, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'SEPA'), (1, 'Credit Card'), (2, 'PayPal')], default=0, editable=False, verbose_name='Payment Type'),
        ),
    ]
