# Generated by Django 2.1.10 on 2019-10-03 16:30

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import wechange_payments.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wechange_payments', '0004_auto_20190927_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Not created at provider.'), (1, 'Created, but not finalized'), (2, 'Finalized, but not downloaded'), (3, 'Downloaded and ready')], default=0, editable=False, help_text="An invoice's state can only ever increase.", verbose_name='Invoice State')),
                ('is_ready', models.BooleanField(default=False, help_text='An indicator flag to show that the invoice has been created in the invoice provider and can be downloaded', verbose_name='Is Ready')),
                ('file', models.FileField(blank=True, editable=False, max_length=250, null=True, upload_to=wechange_payments.utils.utils._get_invoice_filename, verbose_name='File')),
                ('provider_id', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Provider Invoice ID')),
                ('backend', models.CharField(editable=False, max_length=255, verbose_name='Invoice Provider Backend class used')),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This may contain the download path or similar IDs to retrieve the file from the provider.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_action_at', models.DateTimeField(auto_now=True, help_text='Used to indicate when the last attempt to retrieve the invoice from the provider was made, so not to spam them in case their API is down.', verbose_name='Last Action At')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.OneToOneField(editable=False, help_text='The first payment for this subscription, which is also used to book any future payments.', on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='wechange_payments.Payment', verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
