# Generated by Django 2.1.10 on 2019-10-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechange_payments', '0005_auto_20191003_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created',), 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Cancelled by User'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='terminated',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Finally terminated by System'),
        ),
    ]
