# Generated by Django 2.1.10 on 2019-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechange_payments', '0006_auto_20191020_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('0', 'SEPA'), ('1', 'Credit Card'), ('2', 'PayPal')], default='0', editable=False, max_length=50, verbose_name='Payment Type'),
        ),
    ]
