# Generated by Django 2.1.10 on 2019-11-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechange_payments', '0008_convert_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_postponed_payment',
            field=models.BooleanField(default=False, editable=False, help_text='Is this a postponed payment, that gets pre-authorized first, and then cashed-in at some later point?', verbose_name='Is postponed payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'Payment initiated but not completed by user yet'), (2, 'Payment processing'), (3, 'Successfully paid'), (301, 'Pre-authorized for payment, but not yet paid'), (101, 'Failed'), (102, 'Retracted'), (103, 'Canceled')], default=0, editable=False, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('dd', 'Direct Debit (SEPA)'), ('cc', 'Credit Card'), ('paypal', 'PayPal')], default='dd', editable=False, max_length=50, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Terminated.'), (1, 'Cancelled, but still active'), (2, 'Active'), (3, 'Waiting, becoming active at next payment due date'), (99, 'Suspended, because of payment errors')], default=0, editable=False, help_text='A subscription can only ever go from higher number states to lower number states, never back up again!', verbose_name='Subscription State'),
        ),
    ]
