# Generated by Django 2.1.10 on 2019-11-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechange_payments', '0009_auto_20191105_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
