# Generated by Django 2.1.10 on 2019-11-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechange_payments', '0010_auto_20191111_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Terminated.'), (1, 'Cancelled, but still active'), (2, 'Active'), (99, 'Suspended, because of payment errors')], default=0, editable=False, help_text='A subscription can only ever go from higher number states to lower number states, never back up again!', verbose_name='Subscription State'),
        ),
    ]
