# Generated by Django 2.1.10 on 2019-12-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechange_payments', '0012_subscription_num_attempts_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='organisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
