# Generated by Django 2.1.10 on 2019-12-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechange_payments', '0013_payment_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_pre_notification_at',
            field=models.DateTimeField(blank=True, help_text='Determines whether a pre-notification for the next due payment should be or has been sent.', null=True, verbose_name='Last pre-notification at'),
        ),
    ]
