# Generated by Django 3.2 on 2022-01-17 16:42

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechange_payments', '0014_subscription_last_pre_notification_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='extra_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='This may contain the download path or similar IDs to retrieve the file from the provider.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
