# -*- coding: utf-8 -*-

from wechange_payments.conf import settings
from django.db import models
from django.contrib.postgres.fields.jsonb import JSONField
from django.utils.translation import ugettext_lazy as _


class Payment(models.Model):
    
    TYPE_SEPA = 0
    
    #: Choices for :attr:`type`: ``(int, str)``
    TYPE_CHOICES = (
        (TYPE_SEPA, _('SEPA')),
    )
    
    user = models.OneToOneField(settings.AUTH_USER_MODEL, editable=False,
        related_name='payments', on_delete=models.CASCADE, null=True)
    vendor_transaction_id = models.CharField(_('Vendor Transaction Id'), max_length=50,
        help_text='An Id for the payment generated by the Payment Service')
    internal_transaction_id = models.CharField(_('Internal Transaction Id'), max_length=50,
        help_text='An Id for the payment generated by us')
    amount = models.FloatField(default='0.0')
    type = models.PositiveSmallIntegerField(_('Project Type'), blank=False,
        default=TYPE_SEPA, choices=TYPE_CHOICES, editable=False)
    completed_at = models.DateTimeField(verbose_name=_('Completed At'), editable=False, auto_now_add=True)
    backend = models.CharField(_('Backend class used'), max_length=50)
    extra_data = JSONField()
    
    class Meta(object):
        app_label = 'wechange_payments'
        verbose_name = _('Portal')
        verbose_name_plural = _('Portals')


class TransactionLog(models.Model):
    
    TYPE_REQUEST = 0
    TYPE_POSTBACK = 1
    
    #: Choices for :attr:`type`: ``(int, str)``
    TYPE_CHOICES = (
        (TYPE_REQUEST, _('Direct Request')),
        (TYPE_POSTBACK, _('Received Postback')),
    )
    
    url = models.CharField(_('API Endpoint URL'), max_length=150, null=True, blank=True)
    type = models.PositiveSmallIntegerField(_('Project Type'), blank=False,
        default=TYPE_REQUEST, choices=TYPE_CHOICES, editable=False)
    data = JSONField()

